#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 480
#define MAP_WIDTH 640
#define MAP_HEIGHT 480
#define CELL_SIZE 10
#define MAP_COLUMNS (MAP_WIDTH / CELL_SIZE)
#define MAP_ROWS (MAP_HEIGHT/ CELL_SIZE)
#define FOV 60.0f
#define RAY_LENGTH 500
#define DEBUG true
#define SHOW2D true